fix(tlua): `tlua::error!` should not default to never type
Otherwise, we get the following obscure error:

```
---- tarantool/tlua/src/macros.rs - macros::error (line 103) stdout ----
error: this function depends on never type fallback being `()`
   --> tarantool/tlua/src/macros.rs:104:38
    |
104 | fn main() { #[allow(non_snake_case)] fn _doctest_main_tarantool_tlua_src_macros_rs_103_0() {
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in Rust 2024 and in a future release in all editions!
    = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/never-type-fallback.html>
    = help: specify the types explicitly
note: in edition 2024, the requirement `!: PushInto<InsideCallback>` will fail
   --> tarantool/tlua/src/macros.rs:106:5
    |
106 | lua.set("rust_callback_which_may_throw",
    |     ^^^
    = note: `#[deny(dependency_on_unit_never_type_fallback)]` (part of `#[deny(rust_2024_compatibility)]`) on by default

error: aborting due to 1 previous error

Couldn't compile the test.
```

(cherry picked from commit 129d3e5ac413204adc6dac86703df2aee151c8b5)