fix(test): mark tests running 26.2.1 on 26.3 catalogue as XFAIL
Instead of erroring with "mismatches the leader's version" like those
tests expects, picodata currently panics while parsing parameters:

panicked at src/config/mod.rs:3406:10:
apply_parameter called only with existing names: Other("No such
parameter with name 'governor_ddl_rpc_timeout'")

This issue was masked by buggy log matching in `fail_to_start`.