build: do cargo update
Don't update blake3 version, otherwise it results in

```
Updating constant_time_eq v0.2.5 -> v0.3.0

error: package `constant_time_eq v0.3.0` cannot be built because it
requires rustc 1.66.0 or newer, while the currently active rustc version
is 1.65.0
```