feat(sql): support IF EXIST and IF NOT EXISTS options
Note that after this merge request, we no longer validate whether the format
of the created object matches with the schema. Consequently, we do not
suppress errors if formats match anymore.

Before:
```sql
CREATE USER u WITH PASSWORD 'Passw0rd'
1
CREATE USER u WITH PASSWORD 'Passw0rd'
0
CREATE USER u WITH PASSWORD 'DifferentPassw0rd'
error: user already exists with different auth method
```

Now:
```sql
CREATE USER u WITH PASSWORD 'Passw0rd'
1
CREATE USER u WITH PASSWORD 'Passw0rd'
error: user u already exists
CREATE USER u WITH PASSWORD 'DifferentPassw0rd'
error: user u already exists
CREATE USER IF NOT EXISTS u WITH PASSWORD 'DifferentPassw0rd'
0
```