feat: support `EXPLAIN (RAW)` for queries that fail in tarantool
Currently, we have a couple of queries that fail at local sql
execution stage(#1394, #1357, #2666). At the same time picodata
is lacking an instrument which helps to analyze the sql executed
in tarantool since `EXPLAIN (RAW)` output will only be returned
if code does not throw any errors during execution.

This commit addresses that issue. Picodata is now able to return
`EXPLAIN (RAW)` output even if query leads to internal tarantool
errors. For instance,

```
admin=> select * from g where max(id) = 42;
ERROR:  sbroad: Failed to compile SQL statement: misuse of aggregate function MAX()
admin=> explain (raw) select * from g where max(id) = 42;
                               QUERY PLAN
-------------------------------------------------------------------------
 1. Query (ROUTER):
 SELECT * FROM "g" WHERE max (CAST ("g"."id" as int)) = CAST(42 AS int)
 +---------------------------------------------------------------------+
 | Failed to compile SQL statement: misuse of aggregate function MAX() |
 +---------------------------------------------------------------------+

(6 rows)

```