fix: allow using scalar functions in GROUP BY
Previously, using scalar function in GROUP BY clause led to error:
```
admin=> with t(a) as (select 1) select upper('A') from t group by upper('A');
ERROR:  sbroad: invalid query: aggregate functions are not allowed inside grouping expression. Got aggregate: upper
```

This patch fixes this issue. Now the error is only thrown in case of
aggregate function.

(cherry picked from commit 373f9fa8048730c1e1e87e41e8f17c4d15e20c2b)