test(sql): implement snapshot tests in sql test framework
NOTE: Currently, we only support snapshot updates for `EXPLAIN`.

We write tests as usual, e.g.

```sql
-- TEST: invalid-bucket-calculation-gl2640.2
-- SQL:
EXPLAIN SELECT * FROM t WHERE b = 1;
-- EXPECTED:
projection ("t"."a"::int -> "a", "t"."b"::decimal -> "b")
    selection "t"."b"::decimal = 1::int
        scan "t"
execution options:
    sql_vdbe_opcode_max = 45000
    sql_motion_row_max = 5000
buckets = [1935]
```

Then, when we'd like to update the test, we re-run pytest with a custom
command line argument `--update-sql-snapshots`:

```shell
poetry run pytest -v \
    test/known_defects/sql/test_unstable_bucket_id.py \
    --update-sql-snapshots
```

The framework will show the errors as usual:

```
FAILED test/known_defects/sql/test_unstable_bucket_id.py::TestUnstableBucketId::test_sql[invalid-bucket-calculation-gl2640.5-PgprotoRunner] - assert == failed. [pytest-clarity diff shown]

  LHS vs RHS shown below

  [
      'insert "t" on conflict: fail',
      '    motion [policy: segment([ref("COLUMN_2")]), program: ReshardIfNeeded]',
      '        values',
      '            value row (data=ROW(1::int, 1::int))',
      'execution options:',
      '    sql_vdbe_opcode_max = 45000',
      '    sql_motion_row_max = 5000',
      'buckets = [1934]',
      'buckets = [1935]',
  ]
```

But the test file will be updated in place, so the next test run will pass.