chore: remove dependency on aws-lc-rs brought by pgwire
The problem appeared in form of a failed debian package build. aws-lc-rs
build script was failing with:

thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.19.0/builder/cc_builder.rs:244:13:
Your compiler (cc) is not supported due to a memcmp related bug
reported in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189.We
strongly recommend against using this compiler.

Since we use system openssl we dont need to rely on these backends.

Error message is probably correct, so upgrading the compiler is still a
good idea.