fix(raft): show more context on panic of decoding EntryContext
During operation of the Picodata 25.4.4, a sudden panic occured:

    panicked at src/traft/raft_storage.rs:536:49:
    called `Result::unwrap()` on an `Err` value: Tarantool(DecodeRmpValue(Syntax("data did not match any variant of untagged enum EntryContext")))

It was unexpected, as external factors should not have affected so.
We certainly will not normalize this panic: this is an extraordinary
event, comparable to the WAL journal corruption; at least, as we see
it today.

Due to the conventions outlined above, it was decided to leave the
panic as is, expanding its context - displaying the Entry received from
raft-rs to understand what went wrong. These are temporary measures to
get more context about the error and rule out external factors such as
broken data packets.

Initially, it was hypothesized that the code could (de-)serialize
ambiguously  untagged enums with the members also being untagged enums
(which is a common use case, for example, via `#[serde(flatten)]`,
or see https://github.com/3Hren/msgpack-rust/issues/148 and
https://github.com/3Hren/msgpack-rust/issues/354), or repeating keys
on different levels of enum abstractions were causing ambiguity, or
that there was broken backward compatibility due to the addition of new
fields (however, this is most likely not the case, since all new fields
could be created or filled with empty values without secondary errors).
As a result, none of the hypotheses were confirmed.

Now, this panic looks as follows:

    panicked at src/traft/raft_storage.rs:547:18:
    called `Result::unwrap()` on an `Err` value: Tarantool(DecodeRmpValue(Syntax("data did not match any variant of untagged enum EntryContext: Entry { BYTES HERE }")))