fix: mitigate linker errors caused by changes in cargo
Due to the changes in recent rust toolchains we encountered the
following problem:

```
$ cargo build --all --tests
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "-m64"
...
picodata_plugin-dcde45d91baf2531" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: rust-lld: error: undefined symbol: box_region_used
          >>> referenced by util.rs:213 (picodata-plugin/src/util.rs:213)
          >>>               picodata/picodata/target/debug/deps/picodata_plugin-dcde45d91baf2531.0rqm41eyizggpuzu7kgab3tbl.1sleeyx.rcgu.o:(picodata_plugin::util::test::region_buffer::hc0e4988516f2e499)
          >>> referenced by util.rs:213 (picodata-plugin/src/util.rs:213)
          >>>               picodata/picodata/target/debug/deps/picodata_plugin-dcde45d91baf2531.0rqm41eyizggpuzu7kgab3tbl.1sleeyx.rcgu.o:(picodata_plugin::util::test::region_buffer_big_allocation::h2df11807484fb25e)
          >>> referenced by util.rs:213 (picodata-plugin/src/util.rs:213)
          >>>               picodata/picodata/target/debug/deps/picodata_plugin-dcde45d91baf2531.0rqm41eyizggpuzu7kgab3tbl.1sleeyx.rcgu.o:(picodata_plugin::util::test::region_buffer_tiny_allocation::ha98d29bf1dc63d14)
          >>> referenced 1 more times
...
```

This is caused by cargo feature unification --

```
picodata_plugin = {features = ["internal_test"] }
```

set in picodata's `Cargo.toml` infects other crates in workspace,
such as testplug, picodata_plugin itself and potentially more.

This patch fixes the problem by disabling the affected standalone
test binaries of picodata-plugin and testplug which rely on
stdlib's test harness but are not linked with tarantool symbols.