chore(webui): refactor webui's build rules
This patch introduces the following changes:

* Introduce webui/Makefile as the single source of truth.
* Rewrite build.rs in terms of webui/Makefile.
* Update yarn-related files.

Note that we now have to commit yarn-4.13.0 archive to the repository.
Otherwise we'll see something like this (bare yarn):

```
node:internal/modules/cjs/loader:1478
  throw err;
  ^

Error: Cannot find module 'picodata/webui/.yarn/releases/yarn-4.13.0.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1475:15)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1048:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1072:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1093:12)
    at Module._load (node:internal/modules/cjs/loader:1261:25)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Or (corepack):

```
Internal Error: ENOENT: no such file or directory, stat 'picodata/webui/.yarn/releases/yarn-4.13.0.cjs'
Error: ENOENT: no such file or directory, stat 'picodata/webui/.yarn/releases/yarn-4.13.0.cjs'
```

Further reading: https://github.com/yarnpkg/yarn/issues/7741

(cherry picked from commit d1031a3917cedabce86a34041933a3b7c41e16e2)