fix: update tarantool-module to fix crashes during tlua unwind
Log:

```
i1  | 2024-10-09 02:40:07.850 [135492] main/133/main C> panicked at library/core/src/panicking.rs:221:5:
i1  | panic in a function that cannot unwind
i1  | 2024-10-09 02:40:07.850 [135492] main/133/main C> backtrace:
i1  | disabled backtrace
i1  | 2024-10-09 02:40:07.850 [135492] main/133/main C> aborting due to panic
i1  | [supervisor:135482] no ipc message from child
i1  | [supervisor:135482] subprocess 135492 was signaled with SIGABRT
i1  | [supervisor:135482] core dumped
```